site_name: backstage-demo-k8-sample-component
site_description: 'User documentation for backstage-demo-k8-sample-component'
repo_url: https://github.com/lokeshrangineni/backstage-demo-k8-sample-component
edit_uri: edit/main/README.md

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Documentation for backstage-demo-k8-sample-component: README.md